/**
 * Mandate Types for AP2 Protocol
 *
 * TypeScript implementations of the mandate types as defined in the
 * Google AP2 specification. Mandates represent user intents and signed
 * cart contents in the Agent Payments Protocol.
 */

import type { PaymentRequest } from "./payment_request.ts";
import type { PaymentMandate } from "./payment-mandate.ts";

/**
 * Represents the user's purchase intent.
 *
 * An IntentMandate captures what the user wants to buy in natural language,
 * along with any constraints or preferences they have specified.
 */
export interface IntentMandate {
  /**
   * If false, the agent can make purchases on the user's behalf once
   * all purchase conditions are satisfied.
   *
   * When true, the user must explicitly confirm each cart before purchase.
   * When false, the agent has permission to complete purchases automatically
   * that match the intent and satisfy all specified conditions.
   *
   * @default true
   */
  readonly user_cart_confirmation_required?: boolean;

  /**
   * The natural language description of the user's intent, generated by
   * the shopping agent and confirmed by the user.
   *
   * This should be a clear, specific description of what the user wants
   * to purchase, written in natural language.
   *
   * @example "High top, old school, red basketball shoes"
   * @example "Wireless noise-canceling headphones under $200"
   * @example "Organic coffee beans, medium roast, 2lb bag"
   */
  readonly natural_language_description: string;

  /**
   * Merchants allowed to fulfill the intent.
   *
   * If not set, the shopping agent can work with any suitable merchant.
   * When specified, restricts the agent to only shop with the listed merchants.
   *
   * @example ["nike.com", "adidas.com"]
   * @example ["bestbuy.com"]
   */
  readonly merchants?: readonly string[];

  /**
   * A list of specific product SKUs.
   *
   * If not set, any SKU is allowed that matches the intent.
   * When specified, restricts the agent to only purchase the exact SKUs listed.
   *
   * @example ["NIKE-AIR-JORDAN-1-RED-10", "NIKE-AIR-JORDAN-1-RED-10.5"]
   */
  readonly skus?: readonly string[];

  /**
   * If true, items must be refundable.
   *
   * When set to true, the agent will only consider items that have
   * a refund policy. This provides additional protection for the user.
   *
   * @default false
   */
  readonly requires_refundability?: boolean;

  /**
   * When the intent mandate expires, in ISO 8601 format.
   *
   * After this time, the intent is no longer valid and should not
   * be used to make purchases.
   *
   * @example "2024-12-31T23:59:59Z"
   * @example "2024-03-15T10:30:00-05:00"
   */
  readonly intent_expiry: string;
}

/**
 * The detailed contents of a cart, signed by the merchant to create a CartMandate.
 *
 * CartContents represents the specific items, prices, and terms that a merchant
 * is offering. When signed by the merchant, it becomes a CartMandate.
 */
export interface CartContents {
  /**
   * A unique identifier for this cart.
   *
   * This should be a unique string that identifies this specific cart
   * and its contents.
   *
   * @example "cart_abc123def456"
   * @example "merchant-cart-789012"
   */
  readonly id: string;

  /**
   * If true, the merchant requires user confirmation before purchase.
   *
   * When true, even if the user has given broad purchasing permissions
   * to their agent, this specific cart requires explicit user approval.
   *
   * @example true  // Requires user confirmation
   * @example false // Agent can purchase automatically
   */
  readonly user_cart_confirmation_required: boolean;

  /**
   * W3C PaymentRequest object with purchase details.
   *
   * Contains all the payment details including items, totals, shipping options,
   * and payment methods accepted by the merchant.
   */
  readonly payment_request: PaymentRequest;

  /**
   * When this cart expires, in ISO 8601 format.
   *
   * After this time, the cart contents are no longer valid and should
   * not be used for purchases. Prices and availability may have changed.
   *
   * @example "2024-01-15T14:30:00Z"
   * @example "2024-01-15T09:30:00-05:00"
   */
  readonly cart_expiry: string;

  /**
   * The name of the merchant.
   *
   * Human-readable name of the merchant providing this cart.
   *
   * @example "Nike Store"
   * @example "Best Buy"
   * @example "Amazon"
   */
  readonly merchant_name: string;
}

/**
 * A cart whose contents have been digitally signed by the merchant.
 *
 * A CartMandate represents a merchant's commitment to honor the prices
 * and terms specified in the cart contents, backed by a cryptographic signature.
 */
export interface CartMandate {
  /**
   * The contents of the cart.
   *
   * Contains all the details about items, prices, and terms offered
   * by the merchant.
   */
  readonly contents: CartContents;

  /**
   * Digital signature from the merchant authorizing this cart.
   *
   * This cryptographic signature proves that the merchant has authorized
   * these specific cart contents and commits to honoring the prices and terms.
   * The signature should be verifiable using the merchant's public key.
   *
   * @example "304502210089abcdef..."
   */
  readonly merchant_authorization?: string;
}

/**
 * Union type representing any type of mandate in the AP2 protocol.
 */
export type Mandate = IntentMandate | CartMandate | PaymentMandate;