/**
 * Payment Request Types (Corrected and Final Version)
 *
 * This file defines custom types that EXTEND the standard W3C Payment Request API types.
 * It is explicitly configured to use the "deno.window" library to access global
 * browser types like `PaymentItem`, `PaymentDetailsInit`, etc.
 */

import type { ContactAddress } from "./contact_picker.ts";

/**
 * EXTENSION: An item for purchase with an added `refund_period`.
 * This correctly extends the global `PaymentItem` type.
 */
export interface ExtendedPaymentItem extends PaymentItem {
  /**
   * The refund duration for this item, in days.
   * @default 30
   */
  readonly refund_period: number;
}

/**
 * EXTENSION: Payment details that use our extended item type.
 * This correctly extends the global `PaymentDetailsInit` type.
 */
export interface ExtendedPaymentDetailsInit extends PaymentDetailsInit {
  /** The total amount for the payment, using our extended item type. */
  readonly total: ExtendedPaymentItem;

  /** Individual line items, using our extended item type. */
  readonly displayItems?: readonly ExtendedPaymentItem[];
}

/**
 * APPLICATION-SPECIFIC DATA: A structure representing a complete AP2 payment request.
 *
 * This is a custom interface for your application's logic. It uses the global browser
 * types where possible (e.g., `PaymentMethodData`, `PaymentOptions`).
 */
export interface AP2PaymentRequest {
  /** The unique ID for this payment request. */
  readonly id: string;

  /** A list of supported payment methods. */
  readonly methodData: readonly PaymentMethodData[];

  /** The financial details of the transaction, using our extended details type. */
  readonly details: ExtendedPaymentDetailsInit;

  /** Optional configuration for the payment request. */
  readonly options?: PaymentOptions;

  /** The user's provided shipping address. */
  readonly shipping_address?: ContactAddress;
}

/**
 * APPLICATION-SPECIFIC DATA: A structure representing an AP2 payment response.
 *
 * This is a custom interface for your application's logic. It uses global browser
 * types where possible (e.g., `PaymentShippingOption`).
 */
export interface AP2PaymentResponse {
  /** The unique ID from the original PaymentRequest. */
  readonly requestId: string;

  /** The payment method chosen by the user. */
  readonly methodName: string;

  /** A dictionary generated by a payment method to process a transaction. */
  readonly details?: Record<string, unknown>;

  /** The shipping address provided by the user. */
  readonly shippingAddress?: ContactAddress;

  /** The shipping option selected by the user. */
  readonly shippingOption?: PaymentShippingOption;

  /** The payer's name. */
  readonly payerName?: string;

  /** The payer's email address. */
  readonly payerEmail?: string;

  /** The payer's phone number. */
  readonly payerPhone?: string;
}